// All icons in one place — import from here everywhere in the project
export { 
  FaPhone         as IconPhone,
  FaWhatsapp      as IconWhatsapp,
  FaFacebook      as IconFacebook,
  FaLinkedin      as IconLinkedin,
  FaEnvelope      as IconEmail,
  FaGlobe         as IconGlobe,
  FaFilePdf       as IconPdf,
  FaHeart         as IconHeart,
  FaShieldAlt     as IconShield,
  FaStar          as IconStar,
  FaTrophy        as IconTrophy,
  FaTag           as IconTag,
  FaUsers         as IconPeople,
  FaWrench        as IconWrench,
  FaCog           as IconSettings,
  FaFlask         as IconChemistry,
  FaBolt          as IconEnergy,
  FaTh            as IconGrid,
  FaList          as IconList,
  FaBars          as IconMenu,
  FaTimes         as IconClose,
  FaSearch        as IconSearch,
  FaArrowRight    as IconArrowRight,
  FaArrowLeft     as IconArrowLeft,
  FaCheck         as IconCheck,
  FaCheckCircle   as IconCheckCircle,
  FaMapMarkerAlt  as IconLocation,
  FaClock         as IconClock,
  FaMedal         as IconBadge,
  FaEye           as IconEye,
  FaPaperPlane    as IconPaperPlane,
  FaPlay          as IconPlay,
  FaFilter        as IconFilter,
  FaPalette       as IconDecoration,
  FaTint          as IconAgro,
} from "react-icons/fa";

export {
  MdOutlineMedicalServices as IconMedical,
  MdLocalHospital          as IconHospital,
} from "react-icons/md";